// <auto-generated />
using System;
using CC_Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CC_Demo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831194516_AddCreatedAtAndNormalizedCollections")]
    partial class AddCreatedAtAndNormalizedCollections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CC_Demo.Data.Creator", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AttributionHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "attributionHtml");

                    b.Property<string>("AttributionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "attributionText");

                    b.Property<string>("Copyright")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "copyright");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "dateTimeCreated");

                    b.Property<DateTime>("DatetimeAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "datetimeAdded");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "firstName");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "fullName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "lastName");

                    b.Property<int>("MarvelId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "marvelId");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "middleName");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "modified");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "resource");

                    b.Property<string>("ResourceUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "resourceURI");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "suffix");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasAnnotation("Relational:JsonPropertyName", "thumbnail");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Creators", (string)null);
                });

            modelBuilder.Entity("CC_Demo.Data.Creator", b =>
                {
                    b.OwnsOne("CC_Demo.Models.Marvel.ComicsMarvel", "Comics", b1 =>
                        {
                            b1.Property<string>("CreatorId")
                                .HasColumnType("text");

                            b1.Property<int>("Available")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "available");

                            b1.Property<string>("CollectionUri")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "collectionURI");

                            b1.Property<int>("Returned")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "returned");

                            b1.HasKey("CreatorId");

                            b1.ToTable("CreatorComics", (string)null);

                            b1.HasAnnotation("Relational:JsonPropertyName", "comics");

                            b1.WithOwner()
                                .HasForeignKey("CreatorId");

                            b1.OwnsMany("CC_Demo.Models.Marvel.ItemMarvel", "Items", b2 =>
                                {
                                    b2.Property<string>("CreatorId")
                                        .HasColumnType("text");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "name");

                                    b2.Property<string>("ResourceUri")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "resourceURI");

                                    b2.HasKey("CreatorId", "Id");

                                    b2.ToTable("CreatorComicsItems", (string)null);

                                    b2.HasAnnotation("Relational:JsonPropertyName", "items");

                                    b2.WithOwner()
                                        .HasForeignKey("CreatorId");
                                });

                            b1.Navigation("Items");
                        });

                    b.OwnsOne("CC_Demo.Models.Marvel.EventsMarvel", "Events", b1 =>
                        {
                            b1.Property<string>("CreatorId")
                                .HasColumnType("text");

                            b1.Property<int>("Available")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "available");

                            b1.Property<string>("CollectionUri")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "collectionURI");

                            b1.Property<int>("Returned")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "returned");

                            b1.HasKey("CreatorId");

                            b1.ToTable("CreatorEvents", (string)null);

                            b1.HasAnnotation("Relational:JsonPropertyName", "events");

                            b1.WithOwner()
                                .HasForeignKey("CreatorId");

                            b1.OwnsMany("CC_Demo.Models.Marvel.ItemMarvel", "Items", b2 =>
                                {
                                    b2.Property<string>("CreatorId")
                                        .HasColumnType("text");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "name");

                                    b2.Property<string>("ResourceUri")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "resourceURI");

                                    b2.HasKey("CreatorId", "Id");

                                    b2.ToTable("CreatorEventsItems", (string)null);

                                    b2.HasAnnotation("Relational:JsonPropertyName", "items");

                                    b2.WithOwner()
                                        .HasForeignKey("CreatorId");
                                });

                            b1.Navigation("Items");
                        });

                    b.OwnsOne("CC_Demo.Models.Marvel.SeriesMarvel", "Series", b1 =>
                        {
                            b1.Property<string>("CreatorId")
                                .HasColumnType("text");

                            b1.Property<int>("Available")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "available");

                            b1.Property<string>("CollectionUri")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "collectionURI");

                            b1.Property<int>("Returned")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "returned");

                            b1.HasKey("CreatorId");

                            b1.ToTable("CreatorSeries", (string)null);

                            b1.HasAnnotation("Relational:JsonPropertyName", "series");

                            b1.WithOwner()
                                .HasForeignKey("CreatorId");

                            b1.OwnsMany("CC_Demo.Models.Marvel.ItemMarvel", "Items", b2 =>
                                {
                                    b2.Property<string>("CreatorId")
                                        .HasColumnType("text");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "name");

                                    b2.Property<string>("ResourceUri")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "resourceURI");

                                    b2.HasKey("CreatorId", "Id");

                                    b2.ToTable("CreatorSeriesItems", (string)null);

                                    b2.HasAnnotation("Relational:JsonPropertyName", "items");

                                    b2.WithOwner()
                                        .HasForeignKey("CreatorId");
                                });

                            b1.Navigation("Items");
                        });

                    b.OwnsOne("CC_Demo.Models.Marvel.StoriesMarvel", "Stories", b1 =>
                        {
                            b1.Property<string>("CreatorId")
                                .HasColumnType("text");

                            b1.Property<int>("Available")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "available");

                            b1.Property<string>("CollectionUri")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "collectionURI");

                            b1.Property<int>("Returned")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "returned");

                            b1.HasKey("CreatorId");

                            b1.ToTable("CreatorStories", (string)null);

                            b1.HasAnnotation("Relational:JsonPropertyName", "stories");

                            b1.WithOwner()
                                .HasForeignKey("CreatorId");

                            b1.OwnsMany("CC_Demo.Models.Marvel.ItemWithTypeMarvel", "Items", b2 =>
                                {
                                    b2.Property<string>("CreatorId")
                                        .HasColumnType("text");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "name");

                                    b2.Property<string>("ResourceUri")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "resourceURI");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "type");

                                    b2.HasKey("CreatorId", "Id");

                                    b2.ToTable("CreatorStoriesItems", (string)null);

                                    b2.HasAnnotation("Relational:JsonPropertyName", "items");

                                    b2.WithOwner()
                                        .HasForeignKey("CreatorId");
                                });

                            b1.Navigation("Items");
                        });

                    b.OwnsMany("CC_Demo.Models.Marvel.UrlMarvel", "Urls", b1 =>
                        {
                            b1.Property<string>("CreatorId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Type")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "type");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "url");

                            b1.HasKey("CreatorId", "Id");

                            b1.ToTable("UrlMarvel");

                            b1.HasAnnotation("Relational:JsonPropertyName", "urls");

                            b1.WithOwner()
                                .HasForeignKey("CreatorId");
                        });

                    b.Navigation("Comics")
                        .IsRequired();

                    b.Navigation("Events")
                        .IsRequired();

                    b.Navigation("Series")
                        .IsRequired();

                    b.Navigation("Stories")
                        .IsRequired();

                    b.Navigation("Urls");
                });
#pragma warning restore 612, 618
        }
    }
}
